---
- name: Estimate if installed
  stat:
    path: "{{docker_compose_bin_path}}"
  register: docker_compose_bin

- name: Estimate installed version
  shell: "{{docker_compose_bin_path}} --version"
  when: docker_compose_bin.stat.exists
  register: docker_compose_installed_version

- name: Try to parse installed version
  set_fact:
    installed_version: "{{ docker_compose_installed_version.stdout | regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: '^docker-compose version ([0-9]+\.[0-9][0-9]+\.[0-9]+), build [a-z0-9]+$'
  when: docker_compose_installed_version.stdout is defined
  ignore_errors: True

- name: Try to parse installed version (old)
  set_fact:
    installed_version: "{{ docker_compose_installed_version.stdout | regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: '^docker-compose version: ([0-9]+\.[0-9]+\.[0-9]+)$'
  when: docker_compose_installed_version.stdout is defined and installed_version is not defined

- debug:
    msg: "Installed version: {{ installed_version }}"
  when: installed_version is defined

- debug:
    msg: "Installed version: <none>"
  when: installed_version is not defined
