---
- name: Estimate latest version
  shell: git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "[0-9]+\.[0-9][0-9]+\.[0-9]+$" | tail -n 1
  register: latest_compose_version
  changed_when: False

- name: Use estimated version
  set_fact:
    latest_version: "{{ latest_compose_version.stdout }}"

- debug:
    msg: "Latest available version: {{ latest_version }}"
  when: latest_version is defined
