---
- include: estimate_installed_version.yml

- include: estimate_latest_version.yml
  when: version == ''

- include: estimate_version_to_be_installed.yml

- name: Download bin file
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{version_to_be_installed}}/docker-compose-{{kernel_name}}-{{machine}}"
    dest: "{{docker_compose_bin_path}}"
    mode: 0755
    force: yes
  when: installed_version is not defined or version_to_be_installed != installed_version
