---
- name: install apt dependencies
  apt:
    name:
      - python3-pip
    update_cache: true

- name: install pip package by specified version
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present
    executable: pip3
  when: docker_compose_version is defined
    and docker_compose_version | length > 0

- name: install latest pip package
  pip:
    name: docker-compose
    state: latest  # noqa 403
    executable: pip3
  register: docker_compose_installed_from_pip
  when: docker_compose_version is not defined
    or docker_compose_version | length < 1
