---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should provide docker-compose executable
      command: docker-compose --version
      changed_when: false
      register: docker_compose_version
      failed_when:
        docker_compose_version.stdout != 'docker-compose version 1.26.2, build eefe0d31'
