---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should provide docker-compose executable
      command: docker-compose --version
      changed_when: false
      register: docker_compose_version
      failed_when:
        docker_compose_version.stdout != 'docker-compose version 1.26.2, build eefe0d31'

    - name: Should download bash-completion file
      stat:
        path: /etc/bash_completion.d/docker-compose
        checksum_algorithm: sha256
      register: bash_completion_file
      failed_when: not bash_completion_file.stat.exists

    - name: Validate checksum by re-downloading bash-completion
      get_url:
        url:
          "https://raw.githubusercontent.com/docker/\
          compose/1.26.2/contrib/completion/bash/docker-compose"
        dest: /tmp/docker-compose_bash_completion
        checksum: 'sha256:{{ bash_completion_file.stat.checksum }}'
        mode: 0644
      register: downloaded_docker_compose_bash_completion
