---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: docker-compose-ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

provisioner:
  name: ansible

verifier:
  name: ansible
