---
- name: Verify
  hosts: all
  become: true

  pre_tasks:
    - name: setup regular expressions
      set_fact:
        docker_compose_version_output_regexp:
          new: ^docker-compose version ([0-9]+\.[0-9][0-9]+\.[0-9]+), build ([a-z0-9]+|unknown)$

  tasks:
    - name: Should provide docker-compose executable
      command: docker-compose --version
      changed_when: false
      register: docker_compose_version_output
      failed_when:
        docker_compose_version_output.stdout
        | regex_search(regexp)
        | default('')
        | length < 1
      vars:
        regexp: "{{ docker_compose_version_output_regexp.new }}"

    - name: Should download bash-completion file
      stat:
        path: /etc/bash_completion.d/docker-compose
        checksum_algorithm: sha256
      register: bash_completion_file
      failed_when: not bash_completion_file.stat.exists

    - name: Parse installed version
      set_fact:
        docker_compose_installed_version: "{{
          docker_compose_version_output.stdout
          | regex_search(regexp,'\\1')
          | first
          }}"
      vars:
        regexp: "{{ docker_compose_version_output_regexp.new }}"

    - name: Validate checksum by re-downloading bash-completion
      get_url:
        url:
          "https://raw.githubusercontent.com/docker/\
          compose/{{ docker_compose_installed_version }}/contrib/completion/bash/docker-compose"
        dest: /tmp/docker-compose_bash_completion
        checksum: 'sha256:{{ bash_completion_file.stat.checksum }}'
        mode: 0644
      register: downloaded_docker_compose_bash_completion
