---
- name: Estimate if installed
  stat:
    path: "{{ docker_compose_bin_path }}"
  register: docker_compose_bin

- name: Estimate installed version
  command: "{{ docker_compose_bin_path }} --version"
  when: docker_compose_bin.stat.exists
  register: docker_compose_installed_version_output
  changed_when: false

- name: Try to parse installed version
  set_fact:
    docker_compose_installed_version: "{{
      docker_compose_installed_version_output.stdout
      | regex_search(regexp,'\\1')
      | first
      }}"
  vars:
    regexp: ^docker-compose version ([0-9]+\.[0-9][0-9]+\.[0-9]+), build ([a-z0-9]+|unknown)$
  when: docker_compose_installed_version_output.stdout is defined
  ignore_errors: true

- name: Try to parse installed version (old)
  set_fact:
    docker_compose_installed_version: "{{
      docker_compose_installed_version_output.stdout
      | regex_search(regexp,'\\1')
      | first
      }}"
  vars:
    regexp: '^docker-compose version: ([0-9]+\.[0-9]+\.[0-9]+)$'
  when: docker_compose_installed_version_output.stdout is defined
    and docker_compose_installed_version is not defined

- debug:
    msg: "Installed version: {{ docker_compose_installed_version }}"
  when: docker_compose_installed_version is defined

- debug:
    msg: "Installed version: <none>"
  when: docker_compose_installed_version is not defined
