---
name: Run tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run default tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test

      - name: Run 'install-specific-version' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-specific-version

      - name: Run 'upgrade-to-latest-version' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s upgrade-to-latest-version

      - name: Run 'upgrade-to-specific-version' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s upgrade-to-specific-version

      - name: Run 'install-latest-version-from-pip' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-latest-version-from-pip

      - name: Run 'install-specific-version-from-pip' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-specific-version-from-pip

      - name: Run 'install-latest-bash-completion' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-latest-bash-completion

      - name: Run 'install-specific-bash-completion' tests
        uses: borisskert/molecule-action@v20.11.28
        with:
          arguments: test -s install-specific-bash-completion
